# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 83b74cd7e5b94126ed3321d127bb8babc83ec8c20d6953babb6b5b524d59ae67d9223f492ec1f71434130736b22d2828dfdd286a197c2df509b71b2557feffb2

test:
  secret_key_base: 409223b26ac017627dc0281c6568d047f412aa67aa4f622576fa1839bbb515f664621461e66c18f74ef3cee8ad7dc83f804183f0e2dea156a844be68af443316

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
